### ISSUE TITLE
Segmentation Fault after new Commit

### ISSUE THREAD

**Issue by ChessMan14** [paoloose/urn#14]
Hi there, love the project, but I updated it today and it started segfaulting before the window appears.

GDB says the segfault has something to do with X:

Thread 1 "urn-gtk" received signal SIGSEGV, Segmentation fault.
0x00007ffff6f3a27f in XkbGetUpdatedMap () from /usr/lib/libX11.so.6

BTW, I'm using wayland (but I've tried xwayland too) on arch linux.

**Comment by paoloose** [comment]
Thanks for reporting :) I don't think this is related to latest commits since they basically just update documentation.

Maybe you are dealing with the same problem of this thread: https://github.com/paoloose/urn/issues/9

TL;DR: Wayland doesn't support global hotkeys, so your options are to disable them `gsettings set wildmouse.urn global-hotkeys true` or [forcing](https://wiki.archlinux.org/title/wayland#GTK) an X11 backend:

```shell
GDK_BACKEND=x11 urn-gtk
# instead of just running urn-gtk
```

**Comment by ChessMan14** [comment]
I've already been setting the gdk backend

**Comment by paoloose** [comment]
What about disabling global hotkeys?

**Comment by ChessMan14** [comment]
For some reason, disabling global hotkeys, launching urn, closing it, and then enabling hotkeys seems to fix the crashing issue and allows global hotkeys to work.

**Comment by paoloose** [comment]
Weird. Well, feel free to reopen this if it happens again :)
